services:
  grafana:
    image: grafana/grafana:9.5.2
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning
      - ./dashboards:/etc/grafana/dashboards
    ports:
      - 3010:3000
    networks:
      - grafana-net
    environment:
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-clock-panel,grafana-simple-json-datasource
      - GF_SECURITY_ADMIN_PASSWORD=admin

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - prometheus_data:/etc/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - grafana-net
    command:
      - --config.file=/etc/prometheus/prometheus.yml

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - 9100:9100
    networks:
        - grafana-net

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - 3100:3100
    networks:
      - grafana-net
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    networks:
      - grafana-net
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5500:5432
    networks:
      - grafana-net
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:postgres@postgres:5432/postgres?sslmode=disable"
    ports:
      - 9187:9187
    networks:
      - grafana-net

  tor:
    build:
      context: .
      dockerfile: Dockerfile.tor
    container_name: tor
    ports:
      - 9050:9050  # SOCKS proxy
      - 9051:9051  # Control port
    networks:
      - grafana-net
    volumes:
      - tor_data:/run/tor
      - tor_var:/var/lib/tor
    restart: unless-stopped

  i2pd:
    build:
      context: .
      dockerfile: Dockerfile.i2pd
    container_name: i2pd
    ports:
      - 7070:7070   # HTTP proxy
      - 4444:4444   # HTTP proxy tunnel
      - 4447:4447   # SOCKS proxy
      - 7656:7656   # SAM bridge
    networks:
      - grafana-net
    volumes:
      - i2pd_data:/var/lib/i2pd
    restart: unless-stopped

  lnd:
    build:
      context: .
      dockerfile: Dockerfile.lnd
    container_name: lnd
    ports:
      - 9735:9735  # P2P port
      - 10009:10009  # gRPC port
      - 8080:8080   # REST port
    networks:
      - grafana-net
    volumes:
      - lnd_data:/data/lnd
      - ./lnd.conf:/data/lnd/lnd.conf
      - ./password.txt:/data/lnd/password.txt
      - tor_var:/var/lib/tor:ro
    restart: unless-stopped
    depends_on:
      - postgres
      - tor
      - i2pd
    environment:
      - LND_DATA=/data/lnd

  elements:
    build:
      context: .
      dockerfile: Dockerfile.elements
    container_name: elements
    ports:
      - 7041:7041   # P2P port
      - 18884:18884 # RPC port
    networks:
      - grafana-net
    volumes:
      - elements_data:/home/.elements
      - ./elements.conf:/home/.elements/elements.conf
    restart: unless-stopped
    depends_on:
      - tor
      - i2pd
    environment:
      - ELEMENTS_DATA=/home/.elements

  peerswap:
    build:
      context: .
      dockerfile: Dockerfile.peerswap
    container_name: peerswap
    ports:
      - 42069:42069  # PeerSwap port
    networks:
      - grafana-net
    volumes:
      - peerswap_data:/home/peerswap/.peerswap
      - ./peerswap.conf:/home/peerswap/.peerswap/peerswap.conf
    restart: unless-stopped
    depends_on:
      - lnd
      - elements
    environment:
      - PEERSWAP_DATA=/home/peerswap/.peerswap

networks:
  grafana-net:
    driver: bridge

volumes:
  grafana_data:
  prometheus_data:
  postgres_data:
  lnd_data:
  elements_data:
  tor_data:
  i2pd_data:
  tor_var:
  peerswap_data: