services:

  lnbits:
    build:
      context: .
      dockerfile: ./lnbits/Dockerfile.lnbits
    container_name: lnbits
    restart: unless-stopped
    ports:
      - "5000:5000"
    networks:
      - grafana-net
    volumes:
      - /data/lnbits:/data/lnbits
      - /data/lnd:/home/lnd/.lnd:ro
    environment:
      - TZ=UTC
      - LNBITS_DATA_FOLDER=/data/lnbits
      - LNBITS_RATE_LIMIT_NO=200
      - LNBITS_RATE_LIMIT_PER=minute
      - LNBITS_DATABASE_URL=sqlite:////data/lnbits/database.sqlite3
      - LNBITS_SECRET_KEY=your-secret-key-here
      - HOST=0.0.0.0
      - PORT=5000
      - DEBUG=false
    depends_on:
      - lnd
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  lndg:
    build:
      context: .
      dockerfile: ./lndg/Dockerfile.lndg
    container_name: lndg
    ports:
      - 8889:8889   # LNDG Web UI port
    networks:
      - grafana-net
    volumes:
      - /data/lnd:/root/.lnd:ro
      - /data/lndg:/app/data:rw
    restart: unless-stopped
    depends_on:
      - lnd
    environment:
      - LND_RPC_HOST=lnd:10009
      - LND_NETWORK=mainnet
      # - LND_NETWORK=testnet  # Testnet option (commented)

  peerswap:
    build:
      context: .
      dockerfile: ./peerswap/Dockerfile.peerswap
    container_name: peerswap
    ports:
      - 42069:42069  # PeerSwap port
    networks:
      - grafana-net
    volumes:
      - peerswap_data:/home/peerswap/.peerswap
      - ./peerswap/peerswap.conf:/home/peerswap/.peerswap/peerswap.conf
      - /data/lnd:/home/lnd/.lnd:ro
    restart: unless-stopped
    depends_on:
      - lnd
      - elements
    environment:
      - PEERSWAP_DATA=/home/peerswap/.peerswap

  psweb:
    build:
      context: .
      dockerfile: ./psweb/Dockerfile.psweb
    container_name: psweb
    ports:
      - 1984:1984   # PeerSwap Web UI port
    networks:
      - grafana-net
    volumes:
      - psweb_data:/home/psweb/.peerswap
      - /data/lnd:/home/lnd/.lnd:ro
      - peerswap_data:/home/peerswap/.peerswap
    restart: unless-stopped
    depends_on:
      - peerswap
      - lnd
      - elements
    environment:
      - PSWEB_PORT=1984
      - PEERSWAP_HOST=peerswap:42069
      - LND_HOST=lnd:10009

  thunderhub:
    build:
      context: .
      dockerfile: ./thunderhub/Dockerfile.thunderhub
    container_name: thunderhub
    ports:
      - 3000:3000   # ThunderHub Web UI port
    networks:
      - grafana-net
    volumes:
      - thunderhub_data:/data/thunderhub
      - /data/lnd:/data/lnd:ro  # Volume compartilhado com LND para certificados
    restart: unless-stopped
    depends_on:
      - lnd
    environment:
      - THUNDERHUB_PORT=3000
      - LND_HOST=lnd
      - LND_PORT=10009
      - LND_NETWORK=mainnet
      - NODE_ENV=production
      - ACCOUNT_CONFIG_PATH=/data/thunderhub/config/thubConfig_runtime.yaml

networks:
  grafana-net:
    driver: bridge

volumes:
  grafana_data:
  prometheus_data:
  postgres_data:
  tor_data:
  tor_var:
  peerswap_data:
  psweb_data:
  thunderhub_data:
  lndg_data: