version: '3.8'

services:
  # Bitcoin Core Node
  # bitcoin:
  #   image: pagcoin/brln-bitcoin:latest
  #   container_name: bitcoin
  #   restart: unless-stopped
  #   user: "1007:1007"
  #   ports:
  #     - "8332:8332"
  #     - "8333:8333"
  #     - "28332:28332"
  #     - "28333:28333"
  #   volumes:
  #     - bitcoin_data:/data/bitcoin
  #     - ./container/nodes/bitcoin/bitcoin.conf:/data/bitcoin/bitcoin.conf:ro
  #     - ./container/nodes/bitcoin/i2pd.conf:/etc/i2pd/i2pd.conf:ro
  #   networks:
  #     - brln_network
  #   healthcheck:
  #     test: ["CMD", "bitcoin-cli", "getblockchaininfo"]
  #     interval: 60s
  #     timeout: 30s
  #     retries: 3
  #     start_period: 120s

  # Elements/Liquid Node
  # elements:
  #   image: pagcoin/brln-elements:latest
  #   container_name: elements
  #   restart: unless-stopped
  #   ports:
  #     - "18884:18884"
  #     - "7041:7041"
  #   volumes:
  #     - elements_data:/data/elements
  #     - ./container/nodes/elements/elements.conf:/data/elements/elements.conf:ro
  #   networks:
  #     - internal_network
  #   depends_on:
  #     - bitcoin
  #   healthcheck:
  #     test: ["CMD", "elements-cli", "getblockchaininfo"]
  #     interval: 60s
  #     timeout: 30s
  #     retries: 3
  #     start_period: 120s

  # Tor Network
  tor:
    image: pagcoin/brln-tor:latest
    container_name: tor
    restart: unless-stopped
    user: "1050:1050"
    ports:
      - "9050:9050"
      - "9051:9051"
    volumes:
      - tor_data:/var/lib/tor
    networks:
      - internal_network
    healthcheck:
      test: ["CMD", "curl", "--socks5", "tor:9050", "http://3g2upl4pq6kufc4m.onion"]
      interval: 60s
      timeout: 30s
      retries: 3

  # Lightning Network Daemon (LND)
  lnd:
    image: pagcoin/brln-lnd:latest
    container_name: lnd
    restart: unless-stopped
    user: "1008:1008"
    group_add:
      - "1050"   # adiciona o grupo tor-access (o mesmo usado pelo tor)
    ports:
      - "10009:10009"  # LND RPC
      - "9735:9735"    # Lightning Network P2P
      - "8080:8080"    # LND REST
    volumes:
      - lnd_data:/data/lnd
      - tor_data:/var/lib/tor:ro,z
      - ./container/nodes/lnd/lnd.conf:/data/lnd/lnd.conf:ro
      - ./container/nodes/lnd/password.txt:/data/lnd/password.txt:ro
    networks:
      - internal_network
    depends_on:
      - tor
    environment:
      - LND_DATA_DIR=/data/lnd
    # Override entrypoint for debugging - comment out when done
    entrypoint: ["sleep", "3600"]  # Sleep for 1 hour
    # Disable healthcheck during debugging
    # healthcheck:
    #   test: ["CMD", "lncli", "--network=mainnet", "--rpcserver=localhost:10009", "getinfo"]
    #   interval: 120s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 300s
      
  # # Balance of Satoshis (BOS)
  # bos:
  #   image: pagcoin/brln-bos:latest
  #   container_name: bos
  #   restart: unless-stopped
  #   volumes:
  #     - bos_data:/home/bos/.bos
  #     - lnd_data:/data/lnd:ro
  #   networks:
  #     - brln_network
  #   depends_on:
  #     - lnd
  #   environment:
  #     - BOS_DEFAULT_LND_PATH=/data/lnd

  # # LNBits Lightning Wallet
  # lnbits:
  #   build:
  #     context: ./container/apps/lnbits
  #     dockerfile: Dockerfile.lnbits
  #   container_name: lnbits
  #   restart: unless-stopped
  #   user: "1004:1004"
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - lnbits_data:/data/lnbits
  #     - lnd_data:/data/lnd:ro
  #   networks:
  #     - brln_network
  #   depends_on:
  #     - lnd
  #   environment:
  #     - LNBITS_DATA_FOLDER=/data/lnbits
  #     - LNBITS_DATABASE_URL=sqlite:////data/lnbits/database.sqlite3
  #     - HOST=0.0.0.0
  #     - PORT=5000
  #     - DEBUG=false
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:5000/api/v1/wallet"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3

  # # ThunderHub Lightning Node Manager
  # thunderhub:
  #   build:
  #     context: ./container/apps/thunderhub
  #     dockerfile: Dockerfile.thunderhub
  #   container_name: thunderhub
  #   restart: unless-stopped
  #   user: "1006:1006"
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - thunderhub_data:/data/thunderhub
  #     - lnd_data:/data/lnd:ro
  #   networks:
  #     - brln_network
  #   depends_on:
  #     - lnd
  #   environment:
  #     - THUNDERHUB_PORT=3000
  #     - LND_HOST=lnd:10009
  #     - THUB_PASSWORD=36523152
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:3000"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3

  # LNDg Dashboard
  # lndg:
  #   build:
  #     context: ./container/apps/lndg
  #     dockerfile: Dockerfile.lndg
  #   container_name: lndg
  #   restart: unless-stopped
  #   ports:
  #     - "8889:8889"
  #   volumes:
  #     - lndg_data:/app/data
  #     - lnd_data:/root/.lnd:ro
  #   networks:
  #     - brln_network
  #   depends_on:
  #     - lnd
  #   environment:
  #     - LND_NETWORK=mainnet
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:8889"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3

  # # PeerSwap Daemon
  # peerswap:
  #   build:
  #     context: ./container/apps/peerswap
  #     dockerfile: Dockerfile.peerswap
  #   container_name: peerswap
  #   restart: unless-stopped
  #   user: "1002:1002"
  #   ports:
  #     - "42069:42069"
  #   volumes:
  #     - peerswap_data:/data/peerswap
  #     - lnd_data:/data/lnd:ro
  #     - elements_data:/data/elements:ro
  #   networks:
  #     - brln_network
  #   depends_on:
  #     - lnd
  #     - elements
  #   environment:
  #     - PEERSWAP_DATA=/home/peerswap/.peerswap
  #     - PEERSWAP_LND_HOST=lnd:10009
  #     - PEERSWAP_ELEMENTSD_HOST=elements:18884
  #   healthcheck:
  #     test: ["CMD", "pscli", "listpeers"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3

  # PeerSwap Web Interface
  # psweb:
  #   build:
  #     context: ./container/apps/psweb
  #     dockerfile: Dockerfile.psweb
  #   container_name: psweb
  #   restart: unless-stopped
  #   user: "1006:1006"
  #   ports:
  #     - "1984:1984"
  #   volumes:
  #     - psweb_data:/data/psweb
  #     - lnd_data:/data/lnd:ro
  #   networks:
  #     - brln_network
  #   depends_on:
  #     - peerswap
  #     - lnd
  #   environment:
  #     - PSWEB_PORT=1984
  #     - PEERSWAP_HOST=peerswap:42069
  #     - LND_HOST=lnd:10009
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:1984"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3

# Networks
networks:
  internal_network:
    driver: bridge

# Volumes
volumes:
  # bitcoin_data:

  # elements_data:
  
  tor_data:
  
  lnd_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/lnd
  
  # bos_data:
  
  # lnbits_data:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     o: bind
  #     device: /data/lnbits
  
  # thunderhub_data:
  
  # lndg_data:
  
  # peerswap_data:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     o: bind
  #     device: /data/peerswap
  
  # psweb_data:
