"""Initial schema: Swap, Peer, SwapTransaction, SwapEvent, Asset tables

Revision ID: be1c43128951
Revises: 
Create Date: 2026-01-14 16:54:15.782475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be1c43128951'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.String(length=64), nullable=False),
    sa.Column('asset_name', sa.String(length=128), nullable=False),
    sa.Column('asset_ticker', sa.String(length=16), nullable=True),
    sa.Column('asset_type', sa.String(length=32), nullable=False),
    sa.Column('decimals', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('total_swapped_amount', sa.BigInteger(), nullable=False),
    sa.Column('total_swap_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_asset_id'), 'assets', ['asset_id'], unique=True)
    op.create_table('peers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('peer_pubkey', sa.String(length=66), nullable=False),
    sa.Column('peer_alias', sa.String(length=128), nullable=True),
    sa.Column('connection_type', sa.Enum('LIGHTNING', 'TOR', 'DIRECT', name='connectiontype'), nullable=False),
    sa.Column('tor_onion_address', sa.String(length=128), nullable=True),
    sa.Column('lnd_node_uri', sa.String(length=256), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('reputation_score', sa.Integer(), nullable=False),
    sa.Column('successful_swaps', sa.Integer(), nullable=False),
    sa.Column('failed_swaps', sa.Integer(), nullable=False),
    sa.Column('supported_swap_types', sa.JSON(), nullable=True),
    sa.Column('supported_assets', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_peer_active_lastseen', 'peers', ['is_active', 'last_seen_at'], unique=False)
    op.create_index('idx_peer_reputation', 'peers', ['reputation_score'], unique=False)
    op.create_index(op.f('ix_peers_is_active'), 'peers', ['is_active'], unique=False)
    op.create_index(op.f('ix_peers_last_seen_at'), 'peers', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_peers_peer_pubkey'), 'peers', ['peer_pubkey'], unique=True)
    op.create_table('swaps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('swap_type', sa.Enum('LBTC_TO_LIGHTNING', 'LIGHTNING_TO_LBTC', 'ONCHAIN_TO_LIGHTNING', 'LIGHTNING_TO_ONCHAIN', 'BTC_TO_LBTC', 'LBTC_TO_BTC', 'LIQUID_ASSET_TO_ASSET', 'LIQUID_ASSET_TO_LIGHTNING', name='swapdirection'), nullable=False),
    sa.Column('state', sa.Enum('INITIATED', 'FUNDED', 'CLAIMED', 'REFUNDED', 'EXPIRED', 'FAILED', name='swapstate'), nullable=False),
    sa.Column('payment_hash', sa.String(length=64), nullable=False),
    sa.Column('preimage', sa.String(length=64), nullable=True),
    sa.Column('timeout_block_height', sa.Integer(), nullable=False),
    sa.Column('network_type', sa.Enum('BITCOIN_MAINNET', 'BITCOIN_TESTNET', 'LIQUID_MAINNET', 'LIQUID_TESTNET', name='networktype'), nullable=False),
    sa.Column('initiator_peer_id', sa.UUID(), nullable=False),
    sa.Column('receiver_peer_id', sa.UUID(), nullable=False),
    sa.Column('amount_satoshis', sa.BigInteger(), nullable=False),
    sa.Column('fee_satoshis', sa.BigInteger(), nullable=False),
    sa.Column('funding_txid', sa.String(length=64), nullable=True),
    sa.Column('funding_vout', sa.Integer(), nullable=True),
    sa.Column('claim_txid', sa.String(length=64), nullable=True),
    sa.Column('refund_txid', sa.String(length=64), nullable=True),
    sa.Column('htlc_script_hex', sa.Text(), nullable=False),
    sa.Column('htlc_address', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('funded_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('recovery_file_path', sa.String(length=512), nullable=True),
    sa.Column('lightning_invoice', sa.Text(), nullable=True),
    sa.Column('lightning_payment_request', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['initiator_peer_id'], ['peers.id'], ),
    sa.ForeignKeyConstraint(['receiver_peer_id'], ['peers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_swap_created', 'swaps', ['created_at'], unique=False)
    op.create_index('idx_swap_network_state', 'swaps', ['network_type', 'state'], unique=False)
    op.create_index('idx_swap_state_expires', 'swaps', ['state', 'expires_at'], unique=False)
    op.create_index(op.f('ix_swaps_created_at'), 'swaps', ['created_at'], unique=False)
    op.create_index(op.f('ix_swaps_expires_at'), 'swaps', ['expires_at'], unique=False)
    op.create_index(op.f('ix_swaps_funding_txid'), 'swaps', ['funding_txid'], unique=False)
    op.create_index(op.f('ix_swaps_htlc_address'), 'swaps', ['htlc_address'], unique=False)
    op.create_index(op.f('ix_swaps_payment_hash'), 'swaps', ['payment_hash'], unique=True)
    op.create_index(op.f('ix_swaps_state'), 'swaps', ['state'], unique=False)
    op.create_index(op.f('ix_swaps_swap_type'), 'swaps', ['swap_type'], unique=False)
    op.create_table('swap_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('swap_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('old_state', sa.Enum('INITIATED', 'FUNDED', 'CLAIMED', 'REFUNDED', 'EXPIRED', 'FAILED', name='swapstate'), nullable=True),
    sa.Column('new_state', sa.Enum('INITIATED', 'FUNDED', 'CLAIMED', 'REFUNDED', 'EXPIRED', 'FAILED', name='swapstate'), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['swap_id'], ['swaps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_event_swap_created', 'swap_events', ['swap_id', 'created_at'], unique=False)
    op.create_index('idx_event_type', 'swap_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_swap_events_created_at'), 'swap_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_swap_events_swap_id'), 'swap_events', ['swap_id'], unique=False)
    op.create_table('swap_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('swap_id', sa.UUID(), nullable=False),
    sa.Column('tx_type', sa.String(length=16), nullable=False),
    sa.Column('txid', sa.String(length=64), nullable=False),
    sa.Column('tx_hex', sa.Text(), nullable=False),
    sa.Column('confirmations', sa.Integer(), nullable=False),
    sa.Column('block_height', sa.Integer(), nullable=True),
    sa.Column('block_hash', sa.String(length=64), nullable=True),
    sa.Column('broadcast_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['swap_id'], ['swaps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tx_confirmations', 'swap_transactions', ['confirmations'], unique=False)
    op.create_index('idx_tx_swap_type', 'swap_transactions', ['swap_id', 'tx_type'], unique=False)
    op.create_index(op.f('ix_swap_transactions_swap_id'), 'swap_transactions', ['swap_id'], unique=False)
    op.create_index(op.f('ix_swap_transactions_txid'), 'swap_transactions', ['txid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_swap_transactions_txid'), table_name='swap_transactions')
    op.drop_index(op.f('ix_swap_transactions_swap_id'), table_name='swap_transactions')
    op.drop_index('idx_tx_swap_type', table_name='swap_transactions')
    op.drop_index('idx_tx_confirmations', table_name='swap_transactions')
    op.drop_table('swap_transactions')
    op.drop_index(op.f('ix_swap_events_swap_id'), table_name='swap_events')
    op.drop_index(op.f('ix_swap_events_created_at'), table_name='swap_events')
    op.drop_index('idx_event_type', table_name='swap_events')
    op.drop_index('idx_event_swap_created', table_name='swap_events')
    op.drop_table('swap_events')
    op.drop_index(op.f('ix_swaps_swap_type'), table_name='swaps')
    op.drop_index(op.f('ix_swaps_state'), table_name='swaps')
    op.drop_index(op.f('ix_swaps_payment_hash'), table_name='swaps')
    op.drop_index(op.f('ix_swaps_htlc_address'), table_name='swaps')
    op.drop_index(op.f('ix_swaps_funding_txid'), table_name='swaps')
    op.drop_index(op.f('ix_swaps_expires_at'), table_name='swaps')
    op.drop_index(op.f('ix_swaps_created_at'), table_name='swaps')
    op.drop_index('idx_swap_state_expires', table_name='swaps')
    op.drop_index('idx_swap_network_state', table_name='swaps')
    op.drop_index('idx_swap_created', table_name='swaps')
    op.drop_table('swaps')
    op.drop_index(op.f('ix_peers_peer_pubkey'), table_name='peers')
    op.drop_index(op.f('ix_peers_last_seen_at'), table_name='peers')
    op.drop_index(op.f('ix_peers_is_active'), table_name='peers')
    op.drop_index('idx_peer_reputation', table_name='peers')
    op.drop_index('idx_peer_active_lastseen', table_name='peers')
    op.drop_table('peers')
    op.drop_index(op.f('ix_assets_asset_id'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
