name: Validação de Shell Script

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Executar ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: './shell'
          severity: error

  validate-python:
    name: Validar Python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Analisar com flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
